### ISSUE TITLE
Bug when research 3 was upgraded by 1048576 times

### ISSUE THREAD

**Issue by wengesvip** [spotky1004/Calculator-Evolution#2]
When research 3 was upgraded by 1048576 times, I couldn't upgrade it anymore.

![image](https://user-images.githubusercontent.com/46880981/116069972-993f6d80-a6be-11eb-809b-3a95a089c846.png)

![image](https://user-images.githubusercontent.com/46880981/116070052-b5430f00-a6be-11eb-9cf3-d6ead97dfe65.png)

**Comment by spotky1004** [comment]
I used Parametric Search to calculate how much can buy. To improve performance I had to set it like that.

If you have an idea to fix that, please tell me :D

**Comment by wengesvip** [comment]
Increase mPoint to 33.

But I reached Infinity$ in 5 minutes without completing boost challenge. Is this normal?

**Comment by spotky1004** [comment]
Yep, it's normal.
There's big inflation at that point.
(+ you can complete Booster Challenge after Infinity)
